---
- become: yes
  hosts: default
  tasks:
  - name: install apt-transport-https
    apt:
      name: apt-transport-https
      update_cache: yes
  - name: install ca-certificates
    apt:
      name: ca-certificates
  - name: install gnupg2
    apt:
      name: gnupg2
  - name: add Docker repository
    apt_repository:
      repo: deb https://apt.dockerproject.org/repo debian-jessie main
  - name: add Docker public key
    shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - name: install docker-engine
    apt:
      name: docker-engine
      update_cache: yes
  # Packages install
  - name: Installing packages
    action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=present"
    with_items:
      - python-setuptools
  # Pip install
  - name: Installing dependencies
    easy_install:
      name: pip
  # Docker compose install
  - name: install docker-compose
    pip:
      name: docker-compose
      version: 1.9.0
      state: present
