---
- become: yes
  hosts: all
  tasks:
    - name: base. install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: yes
    - name: base. install ca-certificates
      apt:
        name: ca-certificates
    - name: base. install gnupg2
      apt:
        name: gnupg2
    - name: base. add Docker repository
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo debian-jessie main
    - name: base. add Docker public key
      shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    - name: base. install docker-engine
      apt:
        name: docker-engine
        update_cache: yes
