Vagrant.configure("2") do |config|
  config.vm.define "swarm_manager" do |config|
    config.vm.box = "debian/jessie64"
    config.vm.network "private_network", ip: "10.0.7.10"
    config.vm.provision "ansible", playbook: "playbook.yml"
  end
  config.vm.define "swarm_worker_1" do |config|
    config.vm.box = "debian/jessie64"
    config.vm.network "private_network", ip: "10.0.7.21"
    config.vm.provision "ansible", playbook: "playbook.yml"
  end
  config.vm.define "swarm_worker_2" do |config|
    config.vm.box = "debian/jessie64"
    config.vm.network "private_network", ip: "10.0.7.22"
    config.vm.provision "ansible", playbook: "playbook.yml"
  end
end
