version: '2'
services:
  # ----- Company App Server ------ #
  companyapp-server:
    image: companyapp/server
    container_name: server
    expose:
      - "3000"
  companyapp-webclient:
    image: companyapp/webclient
    container_name: webclient
    expose:
      - "3000"


  # registrator:
  #   image: gliderlabs/registrator:latest
  #   container_name: registrator
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock
  #   command: -internal consul://consul:8500

  # ------ TEST DB ------- #
  #  db:
  #    image: mysql:5.7
  #    restart: always
  #    environment:
  #      MYSQL_ROOT_PASSWORD: mysql
  #      MYSQL_DATABASE: db
  #      MYSQL_USER: mysql
  #      MYSQL_PASSWORD: mysql
