Vagrant.configure("2") do |config|

  config.vm.define "prod_v4" do |prod|
    prod.vm.box = "debian/jessie64"
    prod.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook-prod.yml"
    end
    #prod.vm.network 'private_network', ip: '10.0.0.2'
    prod.vm.network 'private_network', ip: '192.168.10.2'
  end

  config.vm.define "dev_v4" do |dev|
    dev.vm.box = "debian/jessie64"
    dev.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook-dev.yml"
    end
    #dev.vm.network 'private_network', ip: '10.0.0.3'
    dev.vm.network 'private_network', ip: '192.168.10.3'
  end

end
