version: '2'
services:
  # ----- Jon example ------ #
  lia_0:
    image: training/webapp
    expose:
      - "5000"
  lia_1:
    image: training/webapp
    expose:
      - "5000"
  proxy:
    image: nginx
    network_mode: host
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./lia.conf:/etc/nginx/upsteams/lia.conf
