---
  # Copy main.conf file to server
- name: docker_opts. copy main.conf
  copy:
    dest: /etc/systemd/system/docker.service.d/main.conf
    src: upload/main.conf

  # Restart docker service with systemd
- systemd:
    daemon_reload: yes
    name: docker
    state: restarted
